version: 2.1
orbs:
  # orbs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.15"
    steps:
      # install node and checkout code
      - node/install:
          node-version: "14.15"
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      #  Install dependencies in the the backend API
      - run:
          name: backend Install
          command: |
            npm run api:install
      #  Deploy back-end
      - run:
          name: backend deploy
          command: |
            npm run api:deploy
      #  deploy front-end and back-end
      - run:
          name: frontend and backend deploy
          command: |
            npm run deploy
      #  set environmental values to elasticbeanstalk
      - run:
          name: set env
          command: |
            eb setenv POSTGRES_USERNAME=postgres
            eb setenv POSTGRES_PASSWORD=myPassword
            eb setenv POSTGRES_HOST=postgres.czbo2ooqfamw.us-east-1.rds.amazonaws.com
            eb setenv POSTGRES_DB=postgres
            eb setenv AWS_BUCKET=arn:aws:s3:::vegacontactsbucket141092
            eb setenv AWS_REGION=us-east-1
            eb setenv AWS_PROFILE=default
            eb setenv JWT_SECRET=mysecretstring
